// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _lgamfac_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP center(SEXP);
RcppExport SEXP centerscale(SEXP);
RcppExport SEXP lfa_threshold(SEXP, SEXP);
RcppExport SEXP mv(SEXP, SEXP);
RcppExport SEXP tmv(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_lgamfac_rcpp_hello_world", (DL_FUNC) &_lgamfac_rcpp_hello_world, 0},
    {"center",                    (DL_FUNC) &center,                    1},
    {"centerscale",               (DL_FUNC) &centerscale,               1},
    {"lfa_threshold",             (DL_FUNC) &lfa_threshold,             2},
    {"mv",                        (DL_FUNC) &mv,                        2},
    {"tmv",                       (DL_FUNC) &tmv,                       2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lgamfac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
